<?php

namespace Database\Seeders\Questions\Workflow;

use App\Enums\Questionnaire\QuestionType;
use App\Services\Questionnaire\QuestionSeederSyncService;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HealthIsolationMortalityQuestionsSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function (): void {
            $questions = [
                [
                    'seed_key' => 'health.followup_history_model',
                    'title' => 'كيف يجب حفظ تاريخ المتابعة الصحية للحيوان دون اختزال حالته في Status واحد فقط؟',
                    'help_text' => 'المرجع يطلب ملخصًا للحالة الصحية الحالية مع بقاء التفاصيل في سجل المتابعة الصحية. المطلوب حسم هل تكون كل ملاحظة أو مراجعة حدثًا مستقلًا، أم سجلًا حاليًا مع Audit كامل، مع منع فقد التاريخ عند التعافي أو تغير الحالة.',
                    'type' => QuestionType::SINGLE_CHOICE,
                    'is_required' => true,
                    'sort_order' => 1,
                    'report_category' => 'history_rule',
                    'target_entity' => 'health_episode',
                    'options' => [
                        ['label' => 'كل ملاحظة / مراجعة صحية سجل مستقل ضمن Episode صحي ويمكن ربطها بما قبلها', 'value' => 'independent_health_events_with_episode_link'],
                        ['label' => 'سجل صحي حالي واحد مع Audit Trail كامل لكل تغير ومراجعة', 'value' => 'single_current_health_record_with_full_audit'],
                        ['label' => 'تستبدل الحالة الصحية السابقة بالحالة الأحدث', 'value' => 'overwrite_current_health_state'],
                    ],
                ],
                [
                    'seed_key' => 'health.observation_record_fields',
                    'title' => 'ما البيانات التي يجب أن يحتفظ بها سجل الملاحظة أو المتابعة الصحية الفعلية؟',
                    'help_text' => 'الـMVP يحتاج الحد الأدنى الذي يمنع فقد معلومات تؤثر على دورة التشغيل، وليس ملف علاج بيطري كامل. الحقول المقترحة مأخوذة من المرجع الوظيفي ويمكن اختيار ما يلزم منها.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 2,
                    'report_category' => 'field',
                    'target_entity' => 'health_observation',
                    'options' => [
                        ['label' => 'الحيوان', 'value' => 'animal'],
                        ['label' => 'تاريخ / وقت الملاحظة أو المراجعة', 'value' => 'observed_at'],
                        ['label' => 'نوع المشكلة أو الملاحظة', 'value' => 'problem_or_observation'],
                        ['label' => 'درجة الخطورة', 'value' => 'severity'],
                        ['label' => 'الحالة الصحية الناتجة بعد المراجعة', 'value' => 'resulting_health_status'],
                        ['label' => 'قرار الحاجة إلى العزل', 'value' => 'isolation_decision'],
                        ['label' => 'قرار إيقاف عمليات تشغيلية مؤقتًا عند الحاجة', 'value' => 'operational_restriction_decision'],
                        ['label' => 'المستخدم / منفذ المراجعة', 'value' => 'performed_by'],
                        ['label' => 'ملاحظات', 'value' => 'notes'],
                    ],
                ],
                [
                    'seed_key' => 'health.status_categories',
                    'title' => 'ما الحالات الصحية التشغيلية التي يجب أن يدعمها النظام كملخص حالي مشتق من السجل الصحي؟',
                    'help_text' => 'المرجع يقترح حالات مبدئية مثل طبيعي وتحت الملاحظة ومريض ومعزول ومتعافٍ. السؤال يحسم الحالات المطلوبة كملخص تشغيلي، مع بقاء الأحداث التاريخية منفصلة وعدم استخدام Status واحد لوصف كل جوانب الحيوان.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 3,
                    'report_category' => 'state_model_rule',
                    'target_entity' => 'animal_health_state',
                    'options' => [
                        ['label' => 'طبيعي', 'value' => 'normal'],
                        ['label' => 'تحت الملاحظة', 'value' => 'under_observation'],
                        ['label' => 'مريض', 'value' => 'sick'],
                        ['label' => 'معزول', 'value' => 'isolated'],
                        ['label' => 'متعافٍ / في مرحلة العودة للتشغيل', 'value' => 'recovered'],
                    ],
                ],
                [
                    'seed_key' => 'health.operational_restriction_model',
                    'title' => 'كيف يجب تمثيل تأثير الحالة الصحية على السماح بالعمليات التشغيلية مثل التلقيح أو النقل أو الاستمرار في الإنتاج؟',
                    'help_text' => 'المرجع يؤكد أن الحالة الصحية يجب أن تؤثر على الـWorkflow، ويذكر الإيقاف المؤقت عن التلقيح وحالات قد تؤثر على النقل. القواعد التي تحدد أي حالة تمنع أي عملية تبقى في Settings؛ هذا السؤال يحسم هل النتيجة مشتقة من القواعد أم تسجل كقرار حالة محدد.',
                    'type' => QuestionType::SINGLE_CHOICE,
                    'is_required' => true,
                    'sort_order' => 4,
                    'report_category' => 'integration_rule',
                    'target_entity' => 'health_operational_restriction',
                    'options' => [
                        ['label' => 'تشتق القيود تلقائيًا من الحالة الصحية وقواعد Settings دون حفظ قيود مستقلة للحالة', 'value' => 'derive_restrictions_from_health_and_settings'],
                        ['label' => 'تسجل القيود التشغيلية صراحة ضمن الحالة الصحية لكل حيوان', 'value' => 'explicit_case_level_restrictions'],
                        ['label' => 'تشتق القيود الافتراضية من Settings مع إمكانية تسجيل قرار موثق خاص بالحالة عند الحاجة', 'value' => 'derived_defaults_with_documented_case_override'],
                    ],
                ],
                [
                    'seed_key' => 'health.isolation_integration_model',
                    'title' => 'كيف يجب ربط قرار العزل الصحي بحركة النقل الفعلية إلى موقع العزل دون إنشاء سجلَي حركة متنافسين؟',
                    'help_text' => 'المصدر ينص على تسجيل سبب العزل وتاريخه ثم نقل الحيوان إلى قفص عزل وتسجيل حركة النقل. حركة الموقع نفسها Canonical في 4.2؛ المطلوب حسم Boundary بين قرار/فترة العزل وبين حركة التسكين.',
                    'type' => QuestionType::SINGLE_CHOICE,
                    'is_required' => true,
                    'sort_order' => 5,
                    'report_category' => 'integration_rule',
                    'target_entity' => 'health_isolation',
                    'options' => [
                        ['label' => 'ينشأ سجل عزل صحي ويرتبط بحركة نقل Canonical في 4.2، وتبدأ العزلة الفعلية عند اكتمال النقل', 'value' => 'health_isolation_linked_to_completed_housing_transfer'],
                        ['label' => 'يبدأ سجل العزل من قرار العزل فورًا ثم ترتبط به حركة النقل عند تنفيذها', 'value' => 'isolation_starts_on_decision_transfer_follows'],
                        ['label' => 'لا يوجد سجل عزل صحي مستقل؛ النقل إلى موقع عزل هو الذي يمثل العزل بالكامل', 'value' => 'housing_transfer_only_represents_isolation'],
                    ],
                ],
                [
                    'seed_key' => 'health.isolation_record_fields',
                    'title' => 'ما البيانات التي يجب أن يحتفظ بها سجل فترة العزل الصحي؟',
                    'help_text' => 'السجل يصف فترة العزل نفسها، بينما الموقع الفعلي يأتي من 4.2، وموعد توليد مهمة المراجعة وأولويتها من Settings/4.17. يمكن الاحتفاظ بمراجع هذه الأحداث بدل تكرارها.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 6,
                    'report_category' => 'field',
                    'target_entity' => 'health_isolation',
                    'options' => [
                        ['label' => 'الحيوان', 'value' => 'animal'],
                        ['label' => 'مرجع الحالة / الملاحظة الصحية التي أدت إلى العزل', 'value' => 'source_health_reference'],
                        ['label' => 'سبب العزل', 'value' => 'isolation_reason'],
                        ['label' => 'تاريخ / وقت بداية العزل', 'value' => 'started_at'],
                        ['label' => 'مرجع حركة النقل إلى موقع العزل', 'value' => 'isolation_housing_movement_reference'],
                        ['label' => 'مرجع مهمة / مراجعة الحالة عند إنشائها', 'value' => 'review_task_reference'],
                        ['label' => 'تاريخ / وقت نهاية العزل عند انتهائه', 'value' => 'ended_at'],
                        ['label' => 'المستخدم / صاحب القرار أو المنفذ', 'value' => 'performed_by'],
                        ['label' => 'ملاحظات', 'value' => 'notes'],
                    ],
                ],
                [
                    'seed_key' => 'health.recovery_transition_model',
                    'title' => 'بعد تسجيل التعافي، كيف يجب إعادة الحيوان إلى المسار التشغيلي دون افتراض أنه أصبح جاهزًا لكل العمليات تلقائيًا؟',
                    'help_text' => 'المرجع يضع التسلسل: انتهاء الحالة الصحية ثم إعادة تقييم ثم العودة للتشغيل. المطلوب حسم هل التعافي يرفع القيود مباشرة أم ينشئ مرحلة إعادة تقييم قبل استعادة الأهلية التشغيلية.',
                    'type' => QuestionType::SINGLE_CHOICE,
                    'is_required' => true,
                    'sort_order' => 7,
                    'report_category' => 'workflow_transition',
                    'target_entity' => 'health_recovery',
                    'options' => [
                        ['label' => 'يسجل التعافي ويغلق الحالة/العزل، ثم يحتاج الحيوان إعادة تقييم قبل استعادة الأهلية التشغيلية المناسبة', 'value' => 'recovery_then_reevaluation_before_operational_return'],
                        ['label' => 'يسجل التعافي وتعود الأهلية التشغيلية مباشرة وفق Settings الحالية', 'value' => 'recovery_immediate_rule_based_return'],
                        ['label' => 'يسجل التعافي فقط، ولا تغلق القيود أو العزل إلا بقرار تشغيل مستقل لاحق', 'value' => 'recovery_requires_separate_release_decision'],
                    ],
                ],
                [
                    'seed_key' => 'health.recovery_record_fields',
                    'title' => 'ما البيانات التي يجب أن يحتفظ بها حدث التعافي أو إنهاء الحالة الصحية؟',
                    'help_text' => 'التعافي حدث تاريخي مستقل ولا يمحو المشكلة السابقة. يمكن أن ينهي Episode صحيًا أو فترة عزل ويربط بإعادة التقييم أو العودة للتشغيل حسب النموذج المختار.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 8,
                    'report_category' => 'field',
                    'target_entity' => 'health_recovery',
                    'options' => [
                        ['label' => 'الحيوان', 'value' => 'animal'],
                        ['label' => 'مرجع الحالة / Episode الصحي', 'value' => 'health_episode_reference'],
                        ['label' => 'مرجع فترة العزل عند وجودها', 'value' => 'isolation_reference'],
                        ['label' => 'تاريخ / وقت التعافي أو إنهاء الحالة', 'value' => 'recovered_at'],
                        ['label' => 'نتيجة / وصف التعافي', 'value' => 'recovery_outcome'],
                        ['label' => 'مرجع إعادة التقييم أو الإجراء التالي عند إنشائه', 'value' => 'next_review_reference'],
                        ['label' => 'المستخدم / منفذ التسجيل', 'value' => 'performed_by'],
                        ['label' => 'ملاحظات', 'value' => 'notes'],
                    ],
                ],
                [
                    'seed_key' => 'mortality.subject_scopes',
                    'title' => 'ما وحدات التتبع التي يجب أن يستطيع سجل النفوق العام تمثيلها؟',
                    'help_text' => 'بعد الفطام يكون النفوق مرتبطًا بحيوان فردي. قبل الفطام يدير المرجع المواليد كبطن ويمكن تسجيل عدد نافق من البطن؛ التتبع الفردي قبل الفطام لا يفترض إلا إذا كانت الهوية المؤقتة متاحة من 4.7.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 9,
                    'report_category' => 'workflow_scope',
                    'target_entity' => 'mortality_event',
                    'options' => [
                        ['label' => 'حيوان فردي له Animal Record مستقل', 'value' => 'individual_animal'],
                        ['label' => 'عدد من مواليد بطن قبل الفطام', 'value' => 'preweaning_litter_quantity'],
                        ['label' => 'مولود محدد قبل الفطام إذا كان له معرف مؤقت قابل للتتبع', 'value' => 'identified_preweaning_offspring'],
                    ],
                ],
                [
                    'seed_key' => 'mortality.event_record_fields',
                    'title' => 'ما البيانات التي يجب أن يحتفظ بها سجل النفوق الفعلي؟',
                    'help_text' => 'المرجع يذكر الحيوان أو البطن وتاريخ/وقت اكتشاف الحالة والعمر والجنس والوزن الأخير والقفص والمرحلة وسبب النفوق والملاحظات والمسجل. المراجع الحالية مثل الوزن والموقع يفضل ربطها بمصادرها الأصلية بدل إنشاء نسخة متنافسة.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 10,
                    'report_category' => 'field',
                    'target_entity' => 'mortality_event',
                    'options' => [
                        ['label' => 'الحيوان / البطن / المولود موضوع النفوق', 'value' => 'subject'],
                        ['label' => 'العدد النافق عندما يكون الموضوع بطنًا قبل الفطام', 'value' => 'mortality_count'],
                        ['label' => 'تاريخ / وقت اكتشاف حالة النفوق', 'value' => 'discovered_at'],
                        ['label' => 'العمر وقت النفوق / الاكتشاف عند إمكان تحديده', 'value' => 'age_at_mortality'],
                        ['label' => 'الجنس عند انطباقه', 'value' => 'sex'],
                        ['label' => 'مرجع آخر وزن صحيح عند وجوده', 'value' => 'last_weight_reference'],
                        ['label' => 'مرجع موقع الإيواء وقت النفوق', 'value' => 'housing_reference'],
                        ['label' => 'المرحلة / السياق التشغيلي وقت النفوق', 'value' => 'operational_stage'],
                        ['label' => 'مرجع سبب النفوق من Master Data عند استخدامه', 'value' => 'mortality_reason_reference'],
                        ['label' => 'المستخدم الذي سجل الحالة', 'value' => 'recorded_by'],
                        ['label' => 'ملاحظات', 'value' => 'notes'],
                    ],
                ],
                [
                    'seed_key' => 'mortality.stage_derivation_model',
                    'title' => 'كيف يجب تحديد المرحلة التشغيلية التي حدث فيها النفوق؟',
                    'help_text' => 'المرجع يفضل استنتاج المرحلة تلقائيًا من حالة الحيوان وقت تسجيل النفوق، مثل تسمين أو حمل أو رضاعة أو قطيع إنتاجي، مع إمكانية الاحتفاظ بالسياق التاريخي المستخدم في التصنيف.',
                    'type' => QuestionType::SINGLE_CHOICE,
                    'is_required' => true,
                    'sort_order' => 11,
                    'report_category' => 'derivation_rule',
                    'target_entity' => 'mortality_event',
                    'options' => [
                        ['label' => 'تستنتج المرحلة من Timeline والحالات النشطة وقت النفوق ولا تخزن يدويًا', 'value' => 'derive_live_from_timeline'],
                        ['label' => 'تستنتج تلقائيًا ويحفظ سجل النفوق لقطة من المرحلة والسياق المستخدم', 'value' => 'derive_and_store_stage_snapshot'],
                        ['label' => 'يسجل المستخدم المرحلة يدويًا مع كل حالة نفوق', 'value' => 'manual_stage_per_mortality_event'],
                    ],
                ],
                [
                    'seed_key' => 'mortality.reason_reference_policy',
                    'title' => 'كيف يجب استخدام سبب النفوق المرجعي الموجود في Master Data عند تسجيل حالة النفوق؟',
                    'help_text' => 'قائمة أسباب النفوق معرفة بالفعل في Master Data وتحتوي أيضًا على «سبب غير معروف» و«سبب آخر». المصدر يقول إن السبب يسجل إذا كان معروفًا، لذلك يجب حسم هل نلزم دائمًا بمرجع أم نسمح بغيابه عندما لا تتوفر معلومة.',
                    'type' => QuestionType::SINGLE_CHOICE,
                    'is_required' => true,
                    'sort_order' => 12,
                    'report_category' => 'validation_rule',
                    'target_entity' => 'mortality_event',
                    'options' => [
                        ['label' => 'مرجع سبب إلزامي دائمًا؛ يستخدم «سبب غير معروف» عند غياب المعلومة، ويطلب وصفًا عند «سبب آخر»', 'value' => 'reason_required_unknown_value_and_other_detail'],
                        ['label' => 'مرجع سبب إلزامي دائمًا؛ قيم «غير معروف» و«سبب آخر» تكفي دون وصف إضافي إلزامي', 'value' => 'reason_required_reference_only'],
                        ['label' => 'مرجع السبب اختياري عند عدم معرفة السبب، ويستخدم Master Data عندما تتوفر معلومة موثوقة', 'value' => 'reason_optional_when_unknown'],
                    ],
                ],
                [
                    'seed_key' => 'mortality.post_event_transition_model',
                    'title' => 'بعد تسجيل النفوق، كيف يجب إغلاق أو تحديث المسارات التشغيلية المرتبطة بالحيوان أو البطن دون حذف التاريخ؟',
                    'help_text' => 'النفوق يغير حالة الوجود ويجب أن ينعكس على الإشغال والمسارات والمهام، كما أن نفوق المواليد أثناء الرضاعة يؤثر على العدد الحالي للبطن دون تعديل أعداد الولادة الأصلية. التنفيذ يجب أن يتكامل مع 4.2 و4.7 و4.17 بدل إنشاء سجلات متعارضة.',
                    'type' => QuestionType::SINGLE_CHOICE,
                    'is_required' => true,
                    'sort_order' => 13,
                    'report_category' => 'integration_rule',
                    'target_entity' => 'mortality_event',
                    'options' => [
                        ['label' => 'حدث النفوق يطلق تحديثات مترابطة تلقائيًا: حالة الوجود، إنهاء الإشغال/المسارات المناسبة، تحديث البطن عند انطباقه، ومعالجة المهام المفتوحة', 'value' => 'automatic_linked_post_mortality_transitions'],
                        ['label' => 'يسجل النفوق أولًا ثم ينشئ إجراءات/مهام معلقة لإغلاق الإشغال والمسارات وتحديث السجلات المرتبطة', 'value' => 'create_pending_post_mortality_actions'],
                        ['label' => 'يسجل النفوق فقط وتنفذ جميع الإغلاقات والتحديثات المرتبطة يدويًا كعمليات مستقلة', 'value' => 'mortality_record_only_manual_followup'],
                    ],
                ],
            ];

            app(QuestionSeederSyncService::class)->sync(
                mainSectionName: 'الحركات ودورة التشغيل الفعلية',
                sectionName: 'الصحة والعزل والتعافي والنفوق',
                questions: $questions,
                prune: true,
                preserveAnswers: true,
            );
        });
    }
}
