<?php

namespace Database\Seeders\Questions\Reports;

use App\Enums\Questionnaire\QuestionType;
use App\Services\Questionnaire\QuestionSeederSyncService;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AlertEarlyWarningDetectionQuestionsSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function (): void {
            $questions = [
                [
                    'seed_key' => 'alert_detection.supported_domains',
                    'title' => 'ما مجالات الحالات التي يجب أن يستطيع نظام التنبيهات اكتشافها وعرضها؟',
                    'help_text' => 'المرجع يميز بين تنبيهات الإنتاج والنمو والصحة والمواقع، ويضيف التنبيه المبكر قبل بعض المواعيد التشغيلية. القواعد الرقمية والـThresholds التي تجعل الحالة تستحق التنبيه تبقى في Settings.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 1,
                    'report_category' => 'alert_scope',
                    'target_entity' => 'alert',
                    'options' => [
                        ['label' => 'تنبيهات الإنتاج والخصوبة', 'value' => 'production_and_fertility'],
                        ['label' => 'تنبيهات النمو والأوزان والتسمين', 'value' => 'growth_weight_and_fattening'],
                        ['label' => 'التنبيهات الصحية والنفوق والعزل', 'value' => 'health_mortality_and_isolation'],
                        ['label' => 'تنبيهات الإشغال والسعة وتشغيل المواقع', 'value' => 'housing_capacity_and_site_operations'],
                        ['label' => 'التنبيهات المبكرة قبل المواعيد التشغيلية المهمة', 'value' => 'scheduled_early_warning'],
                    ],
                ],
                [
                    'seed_key' => 'alert_detection.production_conditions',
                    'title' => 'ما حالات الإنتاج التي يجب أن تكون قابلة للتحويل إلى تنبيهات عند تحقق القواعد المعتمدة؟',
                    'help_text' => 'هذه الحالات مأخوذة من المرجع الوظيفي. هذا السؤال يحدد ما يجب أن يستطيع النظام اكتشافه؛ تحديد الحد العددي أو عدد مرات التكرار الذي يولد التنبيه مكانه Settings.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 2,
                    'report_category' => 'alert_condition',
                    'target_entity' => 'production_alert',
                    'options' => [
                        ['label' => 'تكرار فشل الحمل', 'value' => 'repeated_pregnancy_failure'],
                        ['label' => 'انخفاض معدل الحمل', 'value' => 'low_pregnancy_rate'],
                        ['label' => 'تأخر الولادة عن النطاق المتوقع', 'value' => 'late_expected_birth'],
                        ['label' => 'انخفاض عدد المواليد', 'value' => 'low_litter_size'],
                        ['label' => 'ارتفاع نفوق البطن', 'value' => 'high_litter_mortality'],
                        ['label' => 'انخفاض أداء الأم', 'value' => 'low_female_performance'],
                        ['label' => 'انخفاض أداء الذكر', 'value' => 'low_male_performance'],
                    ],
                ],
                [
                    'seed_key' => 'alert_detection.growth_conditions',
                    'title' => 'ما حالات النمو والتسمين التي يجب أن تكون قابلة للتحويل إلى تنبيهات عند تحقق القواعد المعتمدة؟',
                    'help_text' => 'القيم المستهدفة ومواعيد القياس والفرز وحدود اعتبار النمو ضعيفًا أو متأخرًا لا تحدد هنا؛ التقرير يكتشف فقط أن الحالة تجاوزت قاعدة معتمدة.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 3,
                    'report_category' => 'alert_condition',
                    'target_entity' => 'growth_alert',
                    'options' => [
                        ['label' => 'وزن أقل من المستهدف', 'value' => 'weight_below_target'],
                        ['label' => 'معدل نمو ضعيف', 'value' => 'low_growth_rate'],
                        ['label' => 'تأخر الوصول إلى وزن / جاهزية التسمين المستهدفة', 'value' => 'delayed_fattening_target'],
                        ['label' => 'تجاوز موعد الفرز دون تنفيذ', 'value' => 'sorting_overdue'],
                    ],
                ],
                [
                    'seed_key' => 'alert_detection.health_conditions',
                    'title' => 'ما الحالات الصحية التي يجب أن تكون قابلة للتحويل إلى تنبيهات عند تحقق القواعد المعتمدة؟',
                    'help_text' => 'المصدر يطلب اكتشاف ارتفاع النفوق وتجمعه مكانيًا وتكرار المشاكل الصحية وطول العزل. التقرير يعتمد على السجلات الصحية والنفوق الفعلية، بينما حدود اعتبار الزيادة أو المدة غير طبيعية تبقى في Settings.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 4,
                    'report_category' => 'alert_condition',
                    'target_entity' => 'health_alert',
                    'options' => [
                        ['label' => 'ارتفاع حالات النفوق', 'value' => 'elevated_mortality'],
                        ['label' => 'تجمع حالات النفوق في موقع واحد', 'value' => 'mortality_cluster_by_location'],
                        ['label' => 'تكرار مشكلات أو ملاحظات صحية', 'value' => 'repeated_health_problems'],
                        ['label' => 'تجاوز مدة العزل المتوقعة', 'value' => 'isolation_duration_exceeded'],
                    ],
                ],
                [
                    'seed_key' => 'alert_detection.housing_conditions',
                    'title' => 'ما حالات مواقع الإيواء والسعة التي يجب أن تكون قابلة للتحويل إلى تنبيهات؟',
                    'help_text' => 'حالة الموقع والإشغال والسعة مشتقة من Farm Structure وWorkflow. هنا نحدد الحالات المطلوب اكتشافها فقط؛ مدد الصيانة وحدود السعة والمهلة المطلوبة قبل العجز تحدد في Settings.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 5,
                    'report_category' => 'alert_condition',
                    'target_entity' => 'housing_alert',
                    'options' => [
                        ['label' => 'قفص / عين ممتلئة أو وصلت إلى حد السعة المعتمد', 'value' => 'cage_at_capacity'],
                        ['label' => 'عدم وجود سعة كافية للفطام القادم', 'value' => 'insufficient_capacity_for_upcoming_weaning'],
                        ['label' => 'موقع إيواء تحت الصيانة لفترة طويلة', 'value' => 'site_maintenance_too_long'],
                        ['label' => 'بطارية متوقفة أو غير متاحة بصورة تؤثر على التشغيل', 'value' => 'battery_unavailable_affecting_operations'],
                    ],
                ],
                [
                    'seed_key' => 'early_warning.supported_events',
                    'title' => 'ما الأحداث أو المواعيد التي يجب أن يدعم النظام لها تنبيهًا مبكرًا قبل الاستحقاق؟',
                    'help_text' => 'المرجع يذكر الجس والولادة والفطام والفرز صراحة. عدد الأيام السابقة لكل نوع لا يحدد هنا؛ هو إعداد قابل للضبط في Settings.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 6,
                    'report_category' => 'early_warning_scope',
                    'target_entity' => 'early_warning_alert',
                    'options' => [
                        ['label' => 'فحص الحمل / الجس', 'value' => 'pregnancy_check'],
                        ['label' => 'الولادة المتوقعة', 'value' => 'expected_birth'],
                        ['label' => 'الفطام المتوقع', 'value' => 'expected_weaning'],
                        ['label' => 'الفرز / التقييم القادم', 'value' => 'upcoming_sorting'],
                    ],
                ],
                [
                    'seed_key' => 'early_warning.task_relationship_model',
                    'title' => 'كيف يجب أن يرتبط التنبيه المبكر بالمهمة التشغيلية المرتبطة بنفس الموعد دون إنشاء نسختين متنافستين من العمل المطلوب؟',
                    'help_text' => 'المهمة تمثل إجراءً مطلوب التنفيذ، بينما التنبيه المبكر يلفت الانتباه قبل موعدها. قواعد إنشاء المهمة والتذكير موجودة في Settings و4.17 هو مصدر تنفيذ المهمة.',
                    'type' => QuestionType::SINGLE_CHOICE,
                    'is_required' => true,
                    'sort_order' => 7,
                    'report_category' => 'integration_rule',
                    'target_entity' => 'early_warning_alert',
                    'options' => [
                        ['label' => 'تنبيه مبكر مستقل مرتبط بالمهمة المستقبلية نفسها وبالسياق المصدر', 'value' => 'separate_alert_linked_to_existing_task'],
                        ['label' => 'لا ينشأ Alert Record مستقل؛ تظهر المهمة القادمة مبكرًا وفق إعداد التذكير', 'value' => 'task_visibility_only_no_separate_alert'],
                        ['label' => 'يدعم النموذجان حسب نوع الحدث: Alert مستقل أو إظهار مبكر للمهمة', 'value' => 'configurable_alert_or_early_task_visibility'],
                    ],
                ],
                [
                    'seed_key' => 'alert.record_fields',
                    'title' => 'ما البيانات التي يجب أن يحتفظ بها سجل التنبيه عند إنشائه؟',
                    'help_text' => 'التنبيه يجب أن يكون قابلًا للتفسير والمراجعة والرجوع إلى السبب الذي أنشأه. قيمة الشدة والأولوية إذا كانت مستخدمة تأتي من القاعدة المطبقة في Settings ولا يعاد تعريفها هنا.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 8,
                    'report_category' => 'field',
                    'target_entity' => 'alert',
                    'options' => [
                        ['label' => 'نوع / فئة التنبيه', 'value' => 'alert_type'],
                        ['label' => 'المزرعة', 'value' => 'farm'],
                        ['label' => 'الحيوان أو البطن أو الموقع أو السياق موضوع التنبيه', 'value' => 'subject_reference'],
                        ['label' => 'تاريخ / وقت اكتشاف التنبيه', 'value' => 'detected_at'],
                        ['label' => 'مرجع القاعدة / الشرط الذي أدى إلى اكتشافه', 'value' => 'detection_rule_reference'],
                        ['label' => 'القيمة أو السياق الفعلي الذي أدى إلى التنبيه', 'value' => 'triggering_value_or_context'],
                        ['label' => 'مرجع التقرير أو الحدث أو السجل المصدر عند وجوده', 'value' => 'source_reference'],
                        ['label' => 'الشدة / الأولوية الناتجة من القاعدة عند استخدامها', 'value' => 'derived_severity_or_priority'],
                        ['label' => 'الحالة الحالية للتنبيه', 'value' => 'current_status'],
                        ['label' => 'آخر وقت تم فيه التحقق من استمرار الحالة', 'value' => 'last_evaluated_at'],
                    ],
                ],
                [
                    'seed_key' => 'alert.lifecycle_states',
                    'title' => 'ما حالات Lifecycle التي يجب أن يدعمها سجل التنبيه؟',
                    'help_text' => 'المصدر ينص على أن مشاهدة التنبيه لا تعني انتهاء المشكلة، ويقترح حالات جديد وتمت مشاهدته وتمت معالجته ولم يعد قائمًا. المطلوب الحفاظ على هذا الفصل بوضوح.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 9,
                    'report_category' => 'lifecycle_rule',
                    'target_entity' => 'alert_lifecycle',
                    'options' => [
                        ['label' => 'جديد', 'value' => 'new'],
                        ['label' => 'تمت مشاهدته', 'value' => 'viewed'],
                        ['label' => 'تمت مراجعته / جارٍ التعامل معه', 'value' => 'under_review'],
                        ['label' => 'تمت معالجته', 'value' => 'handled'],
                        ['label' => 'لم يعد قائمًا', 'value' => 'no_longer_active'],
                    ],
                ],
                [
                    'seed_key' => 'alert.lifecycle_history_model',
                    'title' => 'كيف يجب حفظ تاريخ مشاهدة ومراجعة ومعالجة وإغلاق التنبيه؟',
                    'help_text' => 'القسم يحتاج Alert History، لذلك تغيير الحالة الحالية لا يجب أن يمحو من شاهد التنبيه أو راجعه أو متى عولج أو متى زالت الحالة.',
                    'type' => QuestionType::SINGLE_CHOICE,
                    'is_required' => true,
                    'sort_order' => 10,
                    'report_category' => 'history_rule',
                    'target_entity' => 'alert_lifecycle',
                    'options' => [
                        ['label' => 'كل انتقال يسجل كحدث تاريخي مع الوقت والمستخدم والحالة الجديدة', 'value' => 'lifecycle_events_with_actor_and_time'],
                        ['label' => 'سجل التنبيه يحتفظ بالحالة الحالية مع حقول منفصلة لأول مشاهدة وآخر معالجة والإغلاق', 'value' => 'current_state_with_key_lifecycle_timestamps'],
                        ['label' => 'يحتفظ النظام بالحالة الحالية فقط', 'value' => 'current_state_only'],
                    ],
                ],
                [
                    'seed_key' => 'alert.active_condition_deduplication_model',
                    'title' => 'إذا ظلت نفس الحالة غير الطبيعية قائمة عبر عدة مرات فحص، كيف يجب منع إنشاء تنبيهات مكررة بلا داعٍ؟',
                    'help_text' => 'مثال: ارتفاع النفوق في نفس الموقع أو تجاوز حيوان مدة العزل قد يظل صحيحًا عدة أيام. المطلوب الحفاظ على حالة واحدة قابلة للمتابعة بدل إنشاء Alert جديد عند كل إعادة تقييم، إلا إذا تم اعتماد نموذج آخر صراحة.',
                    'type' => QuestionType::SINGLE_CHOICE,
                    'is_required' => true,
                    'sort_order' => 11,
                    'report_category' => 'deduplication_rule',
                    'target_entity' => 'alert',
                    'options' => [
                        ['label' => 'يبقى Alert واحد نشط لنفس نوع الحالة ونفس الموضوع ويحدث آخر وقت تحقق / القيمة الحالية', 'value' => 'single_active_alert_per_condition_subject'],
                        ['label' => 'ينشأ Alert جديد لكل مرة تتحقق فيها القاعدة حتى لو كانت الحالة مستمرة', 'value' => 'new_alert_on_every_detection'],
                        ['label' => 'يبقى Alert رئيسي واحد مع تسجيل Detection Occurrences تاريخية داخله', 'value' => 'single_alert_with_detection_occurrences'],
                    ],
                ],
                [
                    'seed_key' => 'alert.recurrence_after_resolution_model',
                    'title' => 'إذا انتهت الحالة وأغلق التنبيه ثم ظهرت نفس المشكلة مرة أخرى لاحقًا، كيف يجب تمثيل التكرار؟',
                    'help_text' => 'المشكلة الجديدة بعد فترة انتهاء ليست استمرارًا صامتًا للحالة القديمة. المطلوب حسم هل تنشئ Alert جديدًا مع ربطه بالتاريخ السابق أم يعاد فتح نفس السجل.',
                    'type' => QuestionType::SINGLE_CHOICE,
                    'is_required' => true,
                    'sort_order' => 12,
                    'report_category' => 'history_rule',
                    'target_entity' => 'alert_recurrence',
                    'options' => [
                        ['label' => 'إنشاء Alert جديد مع إمكانية ربطه بالتنبيه السابق لنفس الحالة / الموضوع', 'value' => 'new_alert_linked_to_previous_occurrence'],
                        ['label' => 'إعادة فتح نفس Alert القديم والعودة به إلى حالة نشطة', 'value' => 'reopen_existing_alert'],
                        ['label' => 'يعتمد السلوك على نوع التنبيه', 'value' => 'recurrence_model_by_alert_type'],
                    ],
                ],
                [
                    'seed_key' => 'alert.review_action_integration_model',
                    'title' => 'بعد مراجعة التنبيه، كيف يجب ربط الإجراء المتخذ بالسجل دون تنفيذ العملية الفعلية داخل وحدة التقارير؟',
                    'help_text' => 'المسار المرجعي هو بيانات/حدث → تجاوز قاعدة → تنبيه → مراجعة → إجراء. الإجراء الفعلي مثل عزل أو نقل أو وزن أو متابعة يسجل في Workflow المناسب، ويمكن أن ينتج عنه مهمة في 4.17 عند الحاجة.',
                    'type' => QuestionType::SINGLE_CHOICE,
                    'is_required' => true,
                    'sort_order' => 13,
                    'report_category' => 'integration_rule',
                    'target_entity' => 'alert_review',
                    'options' => [
                        ['label' => 'تسجل مراجعة التنبيه ثم يرتبط بالسجل / الحدث Canonical الناتج من الإجراء الفعلي', 'value' => 'review_then_link_canonical_action_event'],
                        ['label' => 'تسجل المراجعة ويمكن إنشاء / ربط مهمة تشغيلية، ثم ترتبط المهمة لاحقًا بالـWorkflow المنفذ', 'value' => 'review_link_task_then_workflow_result'],
                        ['label' => 'تسجل المراجعة والملاحظة فقط دون علاقة مباشرة بالإجراء الناتج', 'value' => 'review_note_only_no_action_link'],
                    ],
                ],
                [
                    'seed_key' => 'alert.resolution_model',
                    'title' => 'كيف يجب التمييز بين «تمت معالجة التنبيه» و«لم تعد الحالة قائمة» عند الإغلاق؟',
                    'help_text' => 'قد ينفذ المستخدم إجراءً لكن الشرط الذي ولد التنبيه يظل قائمًا، كما قد تزول الحالة تلقائيًا بسبب تغير البيانات. لذلك يجب حسم ما إذا كانت المعالجة وزوال الشرط حالتين منفصلتين أم إغلاقًا واحدًا.',
                    'type' => QuestionType::SINGLE_CHOICE,
                    'is_required' => true,
                    'sort_order' => 14,
                    'report_category' => 'resolution_rule',
                    'target_entity' => 'alert_lifecycle',
                    'options' => [
                        ['label' => 'فصل المعالجة عن زوال الحالة: يمكن أن يكون التنبيه معالجًا بينما الشرط ما زال قائمًا، ويغلق نهائيًا عند زواله أو قرار موثق', 'value' => 'handled_separate_from_condition_resolution'],
                        ['label' => 'اعتبار تسجيل المعالجة كافيًا لإغلاق التنبيه حتى لو ظل الشرط قائمًا', 'value' => 'handled_immediately_closes_alert'],
                        ['label' => 'لا يغلق التنبيه إلا عندما يعيد النظام تقييم الشرط ويثبت أنه لم يعد قائمًا', 'value' => 'auto_close_only_when_condition_clears'],
                    ],
                ],
                [
                    'seed_key' => 'alert.drilldown_model',
                    'title' => 'إلى أي مستوى يجب أن يستطيع المستخدم النزول من التنبيه لفهم سبب ظهوره؟',
                    'help_text' => 'التنبيه يجب أن يكون قابلًا للتفسير من الحالة الظاهرة إلى الحيوان أو البطن أو الموقع، ثم إلى التقرير أو القيم والأحداث والسجلات Canonical التي جعلت القاعدة تتحقق.',
                    'type' => QuestionType::SINGLE_CHOICE,
                    'is_required' => true,
                    'sort_order' => 15,
                    'report_category' => 'interaction_rule',
                    'target_entity' => 'alert',
                    'options' => [
                        ['label' => 'عرض رسالة التنبيه فقط', 'value' => 'alert_message_only'],
                        ['label' => 'فتح الكيان / الموضوع المرتبط مع ملخص سبب التنبيه', 'value' => 'drilldown_to_subject_and_trigger_context'],
                        ['label' => 'فتح الموضوع ثم التقرير / القيم والأحداث والسجلات Canonical التي أدت إلى اكتشاف الحالة', 'value' => 'drilldown_to_source_analysis_and_records'],
                    ],
                ],
            ];

            app(QuestionSeederSyncService::class)->sync(
                mainSectionName: 'التقارير والتحليلات والتنبيهات ومؤشرات الأداء',
                sectionName: 'التنبيهات والإنذار المبكر واكتشاف الحالات غير الطبيعية',
                questions: $questions,
                prune: true,
                preserveAnswers: true,
            );
        });
    }
}
