<?php

namespace Database\Seeders\Questions\Reports;

use App\Enums\Questionnaire\QuestionType;
use App\Services\Questionnaire\QuestionSeederSyncService;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HealthMortalityIsolationReportsQuestionsSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function (): void {
            $questions = [
                [
                    'seed_key' => 'health_mortality_report.primary_views',
                    'title' => 'ما العروض الرئيسية التي يجب أن يوفرها قسم تقارير الصحة والنفوق والعزل؟',
                    'help_text' => 'المرجع يحصر النطاق الصحي في الحد التشغيلي المطلوب للـMVP، مع تحليل الملاحظات الصحية والعزل والتعافي والنفوق دون تحويل النظام إلى ملف بيطري تشخيصي كامل.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 1,
                    'report_category' => 'report_scope',
                    'target_entity' => 'health_mortality_report',
                    'options' => [
                        ['label' => 'تقرير الحالات والملاحظات الصحية', 'value' => 'health_observations'],
                        ['label' => 'تقرير العزل وفترات العزل ونتائجها', 'value' => 'isolation_periods'],
                        ['label' => 'تقرير التعافي والعودة للتشغيل', 'value' => 'recovery_and_return'],
                        ['label' => 'تقرير النفوق حسب المرحلة والسياق', 'value' => 'mortality_analysis'],
                        ['label' => 'تحليل تجمعات أو تكرار الحالات غير الطبيعية', 'value' => 'clusters_and_recurrence'],
                    ],
                ],
                [
                    'seed_key' => 'health_report.metrics',
                    'title' => 'ما المؤشرات التي يجب أن يعرضها تقرير الحالات والملاحظات الصحية؟',
                    'help_text' => 'تعتمد هذه المؤشرات على سجل المتابعة الصحية في 4.13 والحالة الصحية الحالية المشتقة منه، ولا تنشئ حالة أو تشخيصًا جديدًا داخل التقرير.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 2,
                    'report_category' => 'report_metric',
                    'target_entity' => 'health_report',
                    'options' => [
                        ['label' => 'عدد الملاحظات / المراجعات الصحية خلال الفترة', 'value' => 'health_observation_count'],
                        ['label' => 'عدد الحيوانات التي لديها حالة صحية نشطة', 'value' => 'animals_with_active_health_case'],
                        ['label' => 'عدد الحيوانات تحت الملاحظة', 'value' => 'animals_under_observation'],
                        ['label' => 'عدد الحيوانات المصنفة حاليًا كمريضة', 'value' => 'currently_sick_animals'],
                        ['label' => 'عدد الحيوانات التي تعافت خلال الفترة', 'value' => 'recovered_animals'],
                        ['label' => 'عدد الحيوانات التي عليها قيود تشغيلية بسبب الحالة الصحية', 'value' => 'health_restricted_animals'],
                        ['label' => 'عدد الحالات حسب درجة الخطورة', 'value' => 'cases_by_severity'],
                    ],
                ],
                [
                    'seed_key' => 'health_report.analysis_dimensions',
                    'title' => 'بأي أبعاد يجب أن يستطيع التقرير تحليل الحالات والملاحظات الصحية؟',
                    'help_text' => 'تصنيف المشكلة ودرجة الخطورة والمرحلة والموقع تأتي من السجلات وMaster Data الحالية. التقرير يستخدمها للتحليل ولا يعيد تعريفها.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 3,
                    'report_category' => 'report_dimension',
                    'target_entity' => 'health_report',
                    'options' => [
                        ['label' => 'تصنيف المشكلة / الملاحظة الصحية', 'value' => 'health_problem_category'],
                        ['label' => 'درجة الخطورة', 'value' => 'severity'],
                        ['label' => 'الحالة الصحية الناتجة', 'value' => 'health_status'],
                        ['label' => 'المرحلة / السياق التشغيلي', 'value' => 'operational_stage'],
                        ['label' => 'العمر / الفئة العمرية', 'value' => 'age_group'],
                        ['label' => 'الجنس', 'value' => 'sex'],
                        ['label' => 'السلالة', 'value' => 'breed'],
                        ['label' => 'المزرعة', 'value' => 'farm'],
                        ['label' => 'العنبر', 'value' => 'barn'],
                        ['label' => 'البطارية', 'value' => 'battery'],
                        ['label' => 'القفص / العين', 'value' => 'cage'],
                    ],
                ],
                [
                    'seed_key' => 'health_report.recurrence_model',
                    'title' => 'كيف يجب أن يتعامل التقرير مع تكرار المشكلة أو الملاحظة الصحية لنفس الحيوان؟',
                    'help_text' => 'المرجع يشدد على الاحتفاظ بالتاريخ وعدم اختزال الحيوان في Status حالي واحد، ويذكر تكرار المشكلات الصحية كحالة تستحق التحليل والتنبيه.',
                    'type' => QuestionType::SINGLE_CHOICE,
                    'is_required' => true,
                    'sort_order' => 4,
                    'report_category' => 'report_model',
                    'target_entity' => 'health_report',
                    'options' => [
                        ['label' => 'يعرض كل Episode / حالة صحية مع احتساب مرات التكرار لنفس الحيوان والتصنيف', 'value' => 'episodes_with_recurrence_count'],
                        ['label' => 'يعرض الحالة الحالية فقط مع إجمالي عدد الملاحظات السابقة', 'value' => 'current_state_with_history_count'],
                        ['label' => 'يعرض آخر ملاحظة صحية فقط دون تحليل التكرار', 'value' => 'latest_observation_only'],
                    ],
                ],
                [
                    'seed_key' => 'isolation_report.metrics',
                    'title' => 'ما المؤشرات التي يجب أن يتضمنها تقرير العزل؟',
                    'help_text' => 'فترة العزل نفسها مسجلة في 4.13، وحركة النقل إلى موقع العزل في 4.2. التقرير يحلل الفترات والنتائج دون تعديلها.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 5,
                    'report_category' => 'report_metric',
                    'target_entity' => 'isolation_report',
                    'options' => [
                        ['label' => 'عدد الحيوانات المعزولة حاليًا', 'value' => 'currently_isolated_animals'],
                        ['label' => 'عدد فترات العزل التي بدأت خلال الفترة', 'value' => 'isolations_started'],
                        ['label' => 'عدد فترات العزل التي انتهت خلال الفترة', 'value' => 'isolations_ended'],
                        ['label' => 'متوسط مدة العزل للفترات المنتهية', 'value' => 'average_completed_isolation_duration'],
                        ['label' => 'عدد حالات العزل التي ما زالت بانتظار مراجعة / إجراء مستحق', 'value' => 'isolations_pending_review'],
                        ['label' => 'توزيع نتائج إنهاء العزل', 'value' => 'isolation_outcome_distribution'],
                    ],
                ],
                [
                    'seed_key' => 'isolation_report.analysis_dimensions',
                    'title' => 'بأي أبعاد يجب أن يستطيع تقرير العزل تقسيم الحالات؟',
                    'help_text' => 'سبب العزل معرف في Master Data، والحالة الصحية والموقع والمرحلة تأتي من السجلات الأصلية. الهدف فهم أسباب ونمط العزل دون إنشاء أسباب تقريرية منفصلة.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 6,
                    'report_category' => 'report_dimension',
                    'target_entity' => 'isolation_report',
                    'options' => [
                        ['label' => 'سبب العزل', 'value' => 'isolation_reason'],
                        ['label' => 'تصنيف المشكلة / الملاحظة الصحية المرتبطة', 'value' => 'health_problem_category'],
                        ['label' => 'درجة الخطورة عند بدء العزل', 'value' => 'starting_severity'],
                        ['label' => 'المرحلة التشغيلية وقت العزل', 'value' => 'operational_stage'],
                        ['label' => 'السلالة', 'value' => 'breed'],
                        ['label' => 'الموقع قبل العزل', 'value' => 'source_housing'],
                        ['label' => 'موقع العزل', 'value' => 'isolation_housing'],
                        ['label' => 'نتيجة انتهاء العزل', 'value' => 'isolation_outcome'],
                    ],
                ],
                [
                    'seed_key' => 'isolation_report.outcomes',
                    'title' => 'ما النتائج التي يجب أن يستطيع تقرير العزل تمييزها عند تحليل نهاية أو استمرار الحالة؟',
                    'help_text' => 'المرجع يذكر عند انتهاء العزل: النتيجة، العودة للقفص أو النقل لموقع جديد، استئناف النشاط أو الاستبعاد. النفوق يظل حدثًا مستقلًا في 4.13 إذا وقع أثناء العزل.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 7,
                    'report_category' => 'report_outcome',
                    'target_entity' => 'isolation_report',
                    'options' => [
                        ['label' => 'العزل ما زال مستمرًا', 'value' => 'isolation_ongoing'],
                        ['label' => 'تعافٍ مع العودة للموقع / المسار السابق', 'value' => 'recovered_and_returned'],
                        ['label' => 'تعافٍ أو انتهاء العزل مع نقل لموقع جديد', 'value' => 'released_to_new_housing'],
                        ['label' => 'انتهاء العزل مع إعادة تقييم قبل استئناف التشغيل', 'value' => 'released_pending_operational_reevaluation'],
                        ['label' => 'انتهاء العزل بقرار استبعاد / تغيير مصير', 'value' => 'released_to_exclusion_or_fate_change'],
                        ['label' => 'نفوق أثناء فترة العزل عند وجود حدث نفوق مسجل', 'value' => 'mortality_during_isolation'],
                    ],
                ],
                [
                    'seed_key' => 'mortality_report.birth_boundary_model',
                    'title' => 'كيف يجب أن يجمع تقرير النفوق الشامل بين النافق عند الولادة والنفوق الذي يحدث بعد الولادة دون خلط مصدر الحدثين؟',
                    'help_text' => 'النافق عند الولادة جزء من حدث الولادة في 4.6، أما النفوق بعد الولادة فهو Mortality Event في 4.13. التقرير يمكن أن يجمعهما تحليليًا بشرط الحفاظ على هذا الفصل ومنع العد المزدوج.',
                    'type' => QuestionType::SINGLE_CHOICE,
                    'is_required' => true,
                    'sort_order' => 8,
                    'report_category' => 'calculation_boundary',
                    'target_entity' => 'mortality_report',
                    'options' => [
                        ['label' => 'عرض تحليلي شامل مع فصل واضح بين النافق عند الولادة والنفوق اللاحق ومصدر كل منهما', 'value' => 'combined_analysis_with_distinct_sources'],
                        ['label' => 'لوحتان منفصلتان داخل نفس التقرير: نفوق الولادة ثم النفوق بعد الولادة', 'value' => 'separate_birth_and_postbirth_panels'],
                        ['label' => 'يقتصر هذا التقرير على Mortality Events بعد الولادة وتبقى بيانات النافق عند الولادة في 5.4 فقط', 'value' => 'postbirth_mortality_only'],
                    ],
                ],
                [
                    'seed_key' => 'mortality_report.stage_categories',
                    'title' => 'ما المراحل التي يجب أن يميزها تقرير النفوق عند تحليل الحالات؟',
                    'help_text' => 'المرجع يطلب الفصل بين مراحل النفوق لأن دلالة الحالة تختلف باختلاف المرحلة. التصنيف يجب أن يأتي من الحدث أو الـTimeline التشغيلي وليس من اختيار تقريري حر.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 9,
                    'report_category' => 'mortality_classification',
                    'target_entity' => 'mortality_report',
                    'options' => [
                        ['label' => 'نافق عند الولادة', 'value' => 'stillborn_at_birth'],
                        ['label' => 'نفوق أثناء الرضاعة قبل الفطام', 'value' => 'lactation_preweaning'],
                        ['label' => 'نفوق بعد الفطام', 'value' => 'post_weaning'],
                        ['label' => 'نفوق أثناء النمو / الفرز', 'value' => 'growth_stage'],
                        ['label' => 'نفوق أثناء التسمين', 'value' => 'fattening_stage'],
                        ['label' => 'نفوق حيوان من القطيع الإنتاجي', 'value' => 'production_herd'],
                        ['label' => 'نفوق أنثى أثناء الحمل', 'value' => 'pregnancy'],
                        ['label' => 'نفوق أنثى أثناء الرضاعة', 'value' => 'lactating_mother'],
                    ],
                ],
                [
                    'seed_key' => 'mortality_report.analysis_dimensions',
                    'title' => 'بأي أبعاد يجب أن يستطيع تقرير النفوق تحليل الحالات؟',
                    'help_text' => 'هذه الأبعاد مذكورة في المرجع الوظيفي لتحليل النفوق وفهم اختلافه بين الأعمار والمراحل والأسباب والسلالات والمواقع.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 10,
                    'report_category' => 'report_dimension',
                    'target_entity' => 'mortality_report',
                    'options' => [
                        ['label' => 'العمر / الفئة العمرية', 'value' => 'age_group'],
                        ['label' => 'المرحلة التشغيلية', 'value' => 'operational_stage'],
                        ['label' => 'سبب النفوق', 'value' => 'mortality_reason'],
                        ['label' => 'السلالة', 'value' => 'breed'],
                        ['label' => 'المزرعة', 'value' => 'farm'],
                        ['label' => 'العنبر', 'value' => 'barn'],
                        ['label' => 'البطارية', 'value' => 'battery'],
                        ['label' => 'القفص / العين', 'value' => 'cage'],
                        ['label' => 'الفترة الزمنية', 'value' => 'time_period'],
                    ],
                ],
                [
                    'seed_key' => 'mortality_report.rate_model',
                    'title' => 'كيف يجب حساب نسبة النفوق عندما تختلف وحدة التعرض للخطر بين المراحل؟',
                    'help_text' => 'المرجع يقترح: عدد حالات النفوق ÷ عدد الحيوانات المعرضة للخطر خلال الفترة، ويؤجل تحديد طريقة الحساب المناسبة لكل مرحلة. هذا السؤال يحسم نموذج الحساب المطلوب دون وضع نسب أو حدود علمية.',
                    'type' => QuestionType::SINGLE_CHOICE,
                    'is_required' => true,
                    'sort_order' => 11,
                    'report_category' => 'calculation_rule',
                    'target_entity' => 'mortality_rate',
                    'options' => [
                        ['label' => 'لكل مرحلة طريقة مقام Exposure مناسبة لها مع تعريفها في Settings / قواعد المؤشرات', 'value' => 'stage_specific_exposure_denominator'],
                        ['label' => 'استخدام مقام موحد يمثل متوسط / عدد الحيوانات الموجودة خلال الفترة لكل المراحل', 'value' => 'single_general_population_denominator'],
                        ['label' => 'عرض أعداد النفوق فقط إلى أن يتم اعتماد مقامات صحيحة لكل مرحلة', 'value' => 'counts_only_until_denominators_approved'],
                    ],
                ],
                [
                    'seed_key' => 'mortality_report.cluster_dimensions',
                    'title' => 'على أي مستويات يجب أن يستطيع النظام اكتشاف وعرض تجمعات النفوق غير الطبيعية؟',
                    'help_text' => 'المرجع يذكر صراحة أن التجمع قد يظهر في عنبر أو بطارية أو قفص أو سلالة. حدود اعتبار التجمع غير طبيعي والفترة المستخدمة في الاكتشاف تبقى في Settings والتنبيهات.',
                    'type' => QuestionType::MULTI_CHOICE,
                    'is_required' => true,
                    'sort_order' => 12,
                    'report_category' => 'cluster_analysis',
                    'target_entity' => 'mortality_cluster_report',
                    'options' => [
                        ['label' => 'المزرعة', 'value' => 'farm'],
                        ['label' => 'العنبر', 'value' => 'barn'],
                        ['label' => 'البطارية', 'value' => 'battery'],
                        ['label' => 'القفص / العين', 'value' => 'cage'],
                        ['label' => 'السلالة', 'value' => 'breed'],
                        ['label' => 'المرحلة التشغيلية', 'value' => 'operational_stage'],
                        ['label' => 'سبب النفوق عند توافره', 'value' => 'mortality_reason'],
                    ],
                ],
                [
                    'seed_key' => 'health_mortality_report.drilldown_model',
                    'title' => 'إلى أي مستوى يجب أن يستطيع المستخدم النزول من مؤشرات الصحة والعزل والنفوق؟',
                    'help_text' => 'الهدف أن تكون الأعداد والنسب والتجمعات قابلة للتفسير بالرجوع إلى الحيوان أو البطن ثم إلى السجل الصحي أو العزل أو حدث النفوق Canonical الذي كوّن المؤشر.',
                    'type' => QuestionType::SINGLE_CHOICE,
                    'is_required' => true,
                    'sort_order' => 13,
                    'report_category' => 'interaction_rule',
                    'target_entity' => 'health_mortality_report',
                    'options' => [
                        ['label' => 'المؤشرات الإجمالية فقط دون Drill-down', 'value' => 'aggregate_only'],
                        ['label' => 'من المؤشر إلى قائمة الحيوانات / البطون الداخلة في الحساب', 'value' => 'drilldown_to_subjects'],
                        ['label' => 'من المؤشر إلى الحيوان / البطن ثم إلى الملاحظات الصحية وفترات العزل وأحداث النفوق والمراجع الأصلية', 'value' => 'drilldown_to_subjects_and_source_records'],
                    ],
                ],
            ];

            app(QuestionSeederSyncService::class)->sync(
                mainSectionName: 'التقارير والتحليلات والتنبيهات ومؤشرات الأداء',
                sectionName: 'تقارير الصحة والنفوق والعزل',
                questions: $questions,
                prune: true,
                preserveAnswers: true,
            );
        });
    }
}
